### ISSUE TITLE
Pac-Man's Renders not working

### ISSUE THREAD

**Issue by JohnsDadsSon** [pokerobybeto/Ultimate-Stream-Tool#1]
Downloaded this and it looks amazing so far! I only have one issue, which is that Pac-Man wont show up as anything other than the random "?". His stock icon seems fine, but no luck with the renders.
Seems unique to pacman too
![pacmanrenderissue](https://user-images.githubusercontent.com/86006233/122234712-000a2780-ceb5-11eb-9a03-0c262c3f7d35.JPG)

**Comment by pokerobybeto** [comment]
It should work fine now
